spring:
    mvc:
        view:
          prefix: /WEB-INF/pages/
          suffix: .jsp
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopcakes?useSSL=false&tinyInt1isBit=false
        password: root
        username: root
        maxWait: 10000
        maxIdle: 30
        maxActive: 50
#        type: javax.sql.DataSource
        name: jdbc/shopcakes
    jpa:
        database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
            ddl-auto: validate
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext